name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build Banane_V1
      run: pio run -e Banane_V1
    - name: Build Banane_V1_proto
      run: pio run -e Banane_V1_proto
    - name: Deploy
      env:
        SUPER_SECRET: ${{ secrets.TOKEN }} 
      run: |
        mv .pio/build/Banane_V1/firmware.bin       matrix_ble_player_Banane_V1.bin
        mv .pio/build/Banane_V1_proto/firmware.bin matrix_ble_player_Banane_V1_proto.bin

        curl -sSF file=@matrix_ble_player_Banane_V1.bin        'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@matrix_ble_player_Banane_V1_proto.bin  'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        
        echo `TZ="Europe/Paris" date '+%F %T'`" git:"`git rev-parse --short HEAD` > matrix_ble_player.info
        curl -sSF file=@matrix_ble_player.info 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET


